------------------------------------------------------------------------------------------
-- Authorization 관련
------------------------------------------------------------------------------------------

--권한그룹정보 ------------------------------

ALTER TABLE COMTNAUTHORGROUPINFO COMMENT = '권한그룹정보';

ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_CREAT_DE` `GROUP_CREAT_DE` char(20) NOT NULL  COMMENT '그룹생성일' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_DC` `GROUP_DC` varchar(100) DEFAULT NULL  COMMENT '그룹설명' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_ID` `GROUP_ID` char(20) NOT NULL DEFAULT ''  COMMENT '그룹ID' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_NM` `GROUP_NM` varchar(60) NOT NULL  COMMENT '그룹명' ;


--권한정보 ------------------------------

ALTER TABLE COMTNAUTHORINFO COMMENT = '권한정보';

ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_CODE` `AUTHOR_CODE` varchar(30) NOT NULL DEFAULT ''  COMMENT '권한코드' ;
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_CREAT_DE` `AUTHOR_CREAT_DE` char(20) NOT NULL  COMMENT '권한생성일' ;
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_DC` `AUTHOR_DC` varchar(200) DEFAULT NULL  COMMENT '권한설명' ;
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_NM` `AUTHOR_NM` varchar(60) NOT NULL  COMMENT '권한명' ;

--롤 계층구조 (*주의: 권한 계층구조) ------------------------------

ALTER TABLE COMTNROLES_HIERARCHY COMMENT = '롤 계층구조';

ALTER TABLE `COMTNROLES_HIERARCHY` CHANGE `CHLDRN_ROLE` `CHLDRN_ROLE` varchar(30) NOT NULL  COMMENT '자식롤' ;
ALTER TABLE `COMTNROLES_HIERARCHY` CHANGE `PARNTS_ROLE` `PARNTS_ROLE` varchar(30) NOT NULL  COMMENT '부모롤' ;

--롤정보 ------------------------------

ALTER TABLE COMTNROLEINFO COMMENT = '롤정보';

ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_CODE` `ROLE_CODE` varchar(50) NOT NULL DEFAULT ''  COMMENT '롤코드' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_CREAT_DE` `ROLE_CREAT_DE` char(20) NOT NULL  COMMENT '롤생성일' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_DC` `ROLE_DC` varchar(200) DEFAULT NULL  COMMENT '롤설명' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_NM` `ROLE_NM` varchar(60) NOT NULL  COMMENT '롤명' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_PTTRN` `ROLE_PTTRN` varchar(300) DEFAULT NULL  COMMENT '롤패턴' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_SORT` `ROLE_SORT` varchar(10) DEFAULT NULL  COMMENT '롤정렬' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_TY` `ROLE_TY` varchar(80) DEFAULT NULL  COMMENT '롤유형' ;

--권한롤관계 ------------------------------

ALTER TABLE COMTNAUTHORROLERELATE COMMENT = '권한롤관계';

ALTER TABLE `COMTNAUTHORROLERELATE` CHANGE `AUTHOR_CODE` `AUTHOR_CODE` varchar(30) NOT NULL  COMMENT '권한코드' ;
ALTER TABLE `COMTNAUTHORROLERELATE` CHANGE `CREAT_DT` `CREAT_DT` datetime DEFAULT NULL  COMMENT '생성일시' ;
ALTER TABLE `COMTNAUTHORROLERELATE` CHANGE `ROLE_CODE` `ROLE_CODE` varchar(50) NOT NULL  COMMENT '롤코드' ;

-- 사용자보안설정 ------------------------------

ALTER TABLE COMTNEMPLYRSCRTYESTBS COMMENT = '사용자보안설정';

ALTER TABLE `COMTNEMPLYRSCRTYESTBS` CHANGE `AUTHOR_CODE` `AUTHOR_CODE` varchar(30) NOT NULL  COMMENT '권한코드' ;
ALTER TABLE `COMTNEMPLYRSCRTYESTBS` CHANGE `MBER_TY_CODE` `MBER_TY_CODE` char(5) DEFAULT NULL  COMMENT '회원유형코드' ;
ALTER TABLE `COMTNEMPLYRSCRTYESTBS` CHANGE `SCRTY_DTRMN_TRGET_ID` `SCRTY_DTRMN_TRGET_ID` varchar(20) NOT NULL  COMMENT '보안설정대상ID' ;

------------------------------------------------------------------------------------------
-- 공통코드 관련
------------------------------------------------------------------------------------------

--공통분류코드 ------------------------------

ALTER TABLE COMTCCMMNCLCODE COMMENT = '공통분류코드';

ALTER TABLE `COMTCCMMNCLCODE` CHANGE `CL_CODE_DC` `CL_CODE_DC` varchar(200) DEFAULT NULL  COMMENT '분류코드설명' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `CL_CODE_NM` `CL_CODE_NM` varchar(60) DEFAULT NULL  COMMENT '분류코드명' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `CL_CODE` `CL_CODE` char(3) NOT NULL  COMMENT '분류코드' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTCCMMNCLCODE` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;

--공통코드 ------------------------------

ALTER TABLE COMTCCMMNCODE COMMENT = '공통코드';

ALTER TABLE `COMTCCMMNCODE` CHANGE `CL_CODE` `CL_CODE` char(3)  COMMENT '분류코드' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `CODE_ID_DC` `CODE_ID_DC` varchar(200) DEFAULT NULL  COMMENT '코드ID설명' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `CODE_ID_NM` `CODE_ID_NM` varchar(60) DEFAULT NULL  COMMENT '코드ID명' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `CODE_ID` `CODE_ID` varchar(6) NOT NULL  COMMENT '코드ID' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTCCMMNCODE` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;

--공통상세코드 ------------------------------

ALTER TABLE COMTCCMMNDETAILCODE COMMENT = '공통상세코드';

ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `CODE_DC` `CODE_DC` varchar(200) DEFAULT NULL  COMMENT '코드설명' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `CODE_ID` `CODE_ID` varchar(6) NOT NULL  COMMENT '코드ID' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `CODE_NM` `CODE_NM` varchar(60) DEFAULT NULL  COMMENT '코드명' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `CODE` `CODE` varchar(15) NOT NULL  COMMENT '코드' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTCCMMNDETAILCODE` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;


------------------------------------------------------------------------------------------
-- 파일 관련
------------------------------------------------------------------------------------------

--파일속성 ------------------------------

ALTER TABLE COMTNFILE COMMENT = '파일속성';

ALTER TABLE `COMTNFILE` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) NOT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNFILE` CHANGE `CREAT_DT` `CREAT_DT` datetime NOT NULL  COMMENT '생성일시' ;
ALTER TABLE `COMTNFILE` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;

--파일상세정보 ------------------------------

ALTER TABLE COMTNFILEDETAIL COMMENT = '파일상세정보';

ALTER TABLE `COMTNFILEDETAIL` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) NOT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_CN` `FILE_CN` mediumtext DEFAULT NULL  COMMENT '파일내용' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_EXTSN` `FILE_EXTSN` varchar(20) NOT NULL  COMMENT '파일확장자' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_SIZE` `FILE_SIZE` decimal(8,0) DEFAULT NULL  COMMENT '파일크기' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_SN` `FILE_SN` decimal(10,0) NOT NULL  COMMENT '파일순번' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_STRE_COURS` `FILE_STRE_COURS` varchar(2000) NOT NULL  COMMENT '파일저장경로' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `ORIGNL_FILE_NM` `ORIGNL_FILE_NM` varchar(255) DEFAULT NULL  COMMENT '원파일명' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `STRE_FILE_NM` `STRE_FILE_NM` varchar(255) NOT NULL  COMMENT '저장파일명' ;

