spring:
  profiles:
    active: prod

---

spring:
  profiles: prod

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true
      path: /h2-console

  #  session:
  #    store-type: redis
  #    redis:
  #      flush-mode: on-save
  #      namespace: spring:session

#  redis:
#    host: localhost
#    #    password: redis
#    port: 6379

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8080
  servlet:
    session:
      timeout: 1800